export const MOVIES_FETCH_START = 'MOVIES_FETCH_START'
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS'
export const MOVIES_FETCH_FAIL = 'MOVIES_FETCH_FAIL'
export const MOVIES_FETCH_FINISH = 'MOVIES_FETCH_FINISH'

export const MOVIES_FETCH_DETAIL_START = 'MOVIES_FETCH_DETAIL_START'
export const MOVIES_FETCH_DETAIL_SUCCESS = 'MOVIES_FETCH_DETAIL_SUCCESS'
export const MOVIES_FETCH_DETAIL_FAIL = 'MOVIES_FETCH_DETAIL_FAIL'
export const MOVIES_FETCH_DETAIL_FINISH = 'MOVIES_FETCH_DETAIL_FINISH'

export const MOVIES_FETCH_DETAIL_VIDEO_START = 'MOVIES_FETCH_DETAIL_VIDEO_START'
export const MOVIES_FETCH_DETAIL_VIDEO_SUCCESS = 'MOVIES_FETCH_DETAIL_VIDEO_SUCCESS'
export const MOVIES_FETCH_DETAIL_VIDEO_FAIL = 'MOVIES_FETCH_DETAIL_VIDEO_FAIL'
export const MOVIES_FETCH_DETAIL_VIDEO_FINISH = 'MOVIES_FETCH_DETAIL_VIDEO_FINISH'
