export const MOVIES_FETCH_START = 'MOVIES_FETCH_START'
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS'
export const MOVIES_FETCH_FAIL = 'MOVIES_FETCH_FAIL'
export const MOVIES_FETCH_FINISH = 'MOVIES_FETCH_FINISH'

export const MOVIES_FETCH_DETAIL_START = 'MOVIES_FETCH_DETAIL_START'
export const MOVIES_FETCH_DETAIL_SUCCESS = 'MOVIES_FETCH_DETAIL_SUCCESS'
export const MOVIES_FETCH_DETAIL_FAIL = 'MOVIES_FETCH_DETAIL_FAIL'
export const MOVIES_FETCH_DETAIL_FINISH = 'MOVIES_FETCH_DETAIL_FINISH'

export const MOVIES_ADD_NEW_START = 'MOVIES_ADD_NEW_START'
export const MOVIES_ADD_NEW_SUCCESS = 'MOVIES_ADD_NEW_SUCCESS'
export const MOVIES_ADD_NEW_FAIL = 'MOVIES_ADD_NEW_FAIL'
export const MOVIES_ADD_NEW_FINISH = 'MOVIES_ADD_NEW_FINISH'

export const MOVIE_DELETE_START = 'MOVIE_DELETE_START'
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS'
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL'
export const MOVIE_DELETE_FINISH = 'MOVIE_DELETE_FINISH'
