export const MOVIES_FETCH_START = 'MOVIES_FETCH_START'
export const MOVIES_FETCH_SUCCESS = 'MOVIES_FETCH_SUCCESS'
export const MOVIES_FETCH_FAIL = 'MOVIES_FETCH_FAIL'
export const MOVIES_FETCH_FINISH = 'MOVIES_FETCH_FINISH'
