export const USER_LOGIN_START = 'USER_LOGIN_START'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_FINISH = 'USER_LOGIN_FINISH'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
